config/routes.rb
Rails.application.routes.draw do

    namespace :user do
      get 'homes/top'
      get 'homes/about'
    end
    namespace :admin do
      get 'homes/top'
    end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
    namespace :admin do
      root to: 'homes#top'
      resources :users, only: [:index, :show, :edit, :update]
      resources :genres, only: [:new, :index, :create, :edit, :update]
      resources :items, only: [:new, :index, :create, :show, :edit, :update] do
        resources :item_comments, only: [:index, :destroy]
      end  
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
      resources :comments, only: [:index, :edit, :destroy, :update, :show]
    end
    
  
    devise_for :users,skip: [:passwords], controllers: {
      registrations: "user/registrations",
      sessions: 'user/sessions'
    }
    

    scope module: :user do
      devise_scope :user do
         post 'users/guest_sign_in', to: 'sessions#new_guest'
      end  
      root to: 'homes#top'

      get 'homes/about' => 'homes#about', as: 'about'
      resources :cows
      resources :pigs
      resources :hens
      get 'items/search' => 'items#search', as: 'search'      
      resources :items, only: [:index, :show] do
        resources :item_comments, only: [:create, :index, :destroy]
      end  
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
      get 'managements/check' => 'managements#check', as: 'check'
      resources :managements, only: [:new, :index, :edit, :create, :update, :show, :destroy]
      resources :reviews, only: [:new, :index, :edit, :create, :update, :show, :destroy]
      get 'users/mypage' => 'users#mypage', as: 'mypage'
      get 'users/show' => 'users#show', as: 'show' 
      get 'users/edit' => 'users#edit', as: 'edit'
      get 'users/confirm' => 'users#confirm', as: 'confirm'
      patch 'users/update' => 'users#update', as: 'update'
      patch 'users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    
      delete 'simulations/destroy_all' => 'simulations#destroy_all', as: 'destroy_all'
      resources :simulations, only: [:index, :update, :destroy, :create]
    end  

  
  
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.all
        @item = Item.new
        @genre = @item.genre
    end    
    
    def new
        @item = Item.new
    end 
    
    def create
        @item = Item.new(item_params)
        @item.save
        redirect_to admin_item_path(@item.id)
    end
    
    def show
        @item = Item.find(params[:id])
        @genre = @item.genre
        @item_comment = ItemComment.new
    end
    
    def edit
        @item = Item.find(params[:id])
        @genre = @item.genre
    end
    
    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to admin_item_path(@item.id)
    end
    
    private
    def item_params
        params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end
  
  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/user/addresses_controller.rb
class User::AddressesController < ApplicationController
  def edit
  end

  def index
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/cows_controller.rb
class User::CowsController < ApplicationController
   before_action :authenticate_user! 
   
   before_action :guest_check
   
  def guest_check
      if current_user.email=='guest@example.com'
        redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
      end
  end        
   
  def new
    @cow = Cow.new    
  end
  
  def create
    @cow = Cow.new(cow_params)
    @cow.user_id = current_user.id
    if @cow.save
      flash[:notice] ='牛の情報を登録しました！'
      redirect_to cow_path(@cow.id)
    else
      @cows = Cow.all
      render :index
    end  
  end    

  def index
    @cows = current_user.cows.all
  end

  def show
    @cow = Cow.find(params[:id])
  end
  
  def edit
    @cow = Cow.find(params[:id])
  end
  
  def update
    @cow = Cow.find(params[:id])
    if @cow.update(cow_params)
      flash[:notice] ='牛の情報を更新しました！'
      redirect_to cow_path(@cow.id)
    else
      render :edit
    end  
  end
  
  def destroy
    @cow = Cow.find(params[:id])
    @cow.destroy
    redirect_to cows_path    
  end
  
  private
  def cow_params
    params.require(:cow).permit(:user_id, :image, :name, :animal_name, :comment, :vaccine, :arrival, :estimated, :mating, :number, :is_active)
  end
end

app/controllers/user/hens_controller.rb
class User::HensController < ApplicationController
  before_action :authenticate_user!  
  
  before_action :guest_check
   
  def guest_check
      if current_user.email=='guest@example.com'
        redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
      end
  end        
   
  def new
    @hen = Hen.new    
  end
  
  def create
    @hen = Hen.new(hen_params)
    @hen.user_id = current_user.id
    if @hen.save
      flash[:notice] ='鶏の情報を登録しました！'
      redirect_to hen_path(@hen.id)
    else
      @hens = Hen.all
      render :index
    end  
  end    

  def index
    @hens = current_user.hens.all
  end

  def show
    @hen = Hen.find(params[:id])
  end
  
  def edit
    @hen = Hen.find(params[:id])
  end
  
  def update
    @hen = Hen.find(params[:id])
    if @hen.update(hen_params)
      flash[:notice] ='鶏の情報を更新しました！'
      redirect_to hen_path(@hen.id)
    else
      render :edit
    end  
  end
  
  def destroy
    @hen = Hen.find(params[:id])
    @hen.destroy
    redirect_to hens_path    
  end
  
  private
  def hen_params
    params.require(:hen).permit(:user_id, :animal_name, :comment, :vaccine, :arrival, :amount, :is_active, :image)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top

  end

  def about
  end
  
end

app/controllers/user/item_comments_controller.rb
class User::ItemCommentsController < ApplicationController
     before_action :authenticate_user!

     before_action :guest_check
     
    def guest_check
        if current_user.email=='guest@example.com'
          redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
        end
    end     

    def create
        item = Item.find(params[:item_id])
        comment = current_user.item_comments.new(item_comment_params)
        comment.item_id = item.id
       if  comment.save
        redirect_to item_path(item)
       else
      redirect_to item_path(item)
       end
        
    end
    
    def destroy
        ItemComment.find(params[:id]).destroy
        redirect_to item_path(params[:item_id])
    end
    
    
    private
    
    def item_comment_params
        params.require(:item_comment).permit(:comment).merge({rate: params[:score]})
    end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
      def search
        @genres = Genre.all        
        if params[:genre_id].present?
          @items = Item.where(genre_id: params[:genre_id]).page(params[:page]).per(4)
        else
          @items = Item.page(params[:page]).per(4)
        end  
      end
  
    def index
        @genres = Genre.all
        if params[:genre_id]
            @genre = Genre.find(params[:genre_id])
            all_items = @genre.items
        else
            all_items = Item.all
        end
        @items = all_items.page(params[:page]).per(4)
    end
    
    def show
        @item = Item.find(params[:id])
        @item_comment = ItemComment.new
    end
    

        
    private
    def item_params
        params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/pigs_controller.rb
class User::PigsController < ApplicationController
   before_action :authenticate_user!  
   
   before_action :guest_check
   
  def guest_check
      if current_user.email=='guest@example.com'
        redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
      end
  end        
   
  def new
    @pig = Pig.new    
  end
  
  def create
    @pig = Pig.new(pig_params)
    @pig.user_id = current_user.id
    if @pig.save
      flash[:notice] ='豚の情報を登録しました！'
      redirect_to pig_path(@pig.id)
    else
      @pig = Pig.all
      render :index
    end  
  end    

  def index
    @pigs = current_user.pigs.all
  end

  def show
    @pig = Pig.find(params[:id])
  end
  
  def edit
    @pig = Pig.find(params[:id])
  end
  
  def update
    @pig = Pig.find(params[:id])
    if @pig.update(pig_params)
      flash[:notice] ='豚の情報を更新しました！'
      redirect_to pig_path(@pig.id)
    else
      render :edit
    end  
  end
  
  def destroy
    @pig = Pig.find(params[:id])
    @pig.destroy
    redirect_to pigs_path    
  end
  
  private
  def pig_params
    params.require(:pig).permit(:user_id, :name, :animal_name, :comment, :vaccine, :arrival, :estimated, :mating, :number, :is_active, :image)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
  #   super(resource)
  show_path(current_user)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_status, only: [:create]
  
  def after_sign_in_path_for(resource)
    show_path(current_user)
  end
    
  def after_sign_out_path_for(resource)
    user_homes_top_path
  end
  
  def new_guest
    user = User.guest
    sign_in user
    redirect_to items_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
  def user_status
    @user = User.find_by(email: params[:user][:email])
    return if !@user
     if @user.valid_password?(params[:user][:password]) && !@user.is_active 
       redirect_to new_user_registration_path
     end  
  end  
end

app/controllers/user/simulations_controller.rb
class User::SimulationsController < ApplicationController
     before_action :authenticate_user!

     before_action :guest_check
     
    def guest_check
        if current_user.email=='guest@example.com'
          redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
        end
    end     
     
    def index
        @simulations = current_user.simulations.all
        @all_price = @simulations.inject(0) { |sum, item| sum + item.sum_of_price }
    end
    
    def create
        @simulation = current_user.simulations.new(simulation_params)
        @simulation_already = current_user.simulations.find_by(item_id: params[:simulation][:item_id])
        if current_user.simulations.find_by(item_id: params[:simulation][:item_id])
            @new_amount = @simulation.amount + @simulation_already.amount
            @simulation_already.update(amount: @new_amount)
            redirect_to simulations_path
        else
            @simulation.save
            redirect_to simulations_path 
        end
        
        
    end
    
    def update
        @simulation = Simulation.find(params[:id])
        @simulation.update(simulation_params)
        redirect_to simulations_path
    end
    
    def destroy
        @simulation = Simulation.find(params[:id])
        @simulation.destroy
        redirect_to simulations_path
    end
    
    def destroy_all
        @simulations = current_user.simulations.all
        @simulations.destroy_all
        redirect_to simulations_path
    end
    
    private
    def simulation_params
        params.require(:simulation).permit(:user_id, :item_id, :amount)
    end    
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/user/items/index.html.erb
<div class="row">
    <div class="col-md-2">
        <div class="border">
            <div class="border-bottom text-center">
                ジャンル検索
            </div>
            <% @genres.each do |genre| %>
                <div class="text-center">
                    <%= link_to genre.name, items_path(genre_id: genre.id)%>
                </div>
            <% end %>
            <div class="border-top text-center">
                <%= link_to '絞り込み機能', search_path%>
            </div>
        </div>
        

    </div>

    <div class="col-md-10">
        <div class="m-2 h3 border-bottom">
          <div class="text-center">商品一覧</div>
        </div>        
            <div class="card-list-container py-5">
                <% @items.each do |item| %>
                <div class="card w-50 mx-auto mt-4 shadow-lg">
                <% if item.is_active %>
            
                      
                            <%= image_tag item.get_image, class:"card-img-top"; %>
                      
                    <div class="card-body">
                        <div class="row">
                            <h4 class="card-title"><%= link_to item.name, item_path(item.id) %></h4>    
                            <h4 class="card-text">￥<%= item.with_tax_price.to_s(:delimited) %></h4>
                            <h5 class="card-text">コメント数<%= item.item_comments.count %></h5>
                        </div>    
                    </div>
                  
                    <% end %>
                    
                </div>
                <% end %>
                <div class="h4 text text-center"><%= paginate @items %></div>
            </div>
    </div>
    
</div>    
    

app/views/user/items/search.html.erb
<div class="row">
    <div class="col-md-2">
        <div class="border">
            <div class="text-center border-bottom">
                 絞り込み機能
            </div>
            <%= form_with url: search_path, method: :get do |form| %>
                <% @genres.each do |genre| %>
                    <div class="text-start">
                        <%= form.check_box :genre_id, { multiple: true }, genre.id, nil %>
                        <%= genre.id %>
                        <%= genre.name %>
                    </div>
                <% end %>
                <div class="text-center">
                    <%= form.submit "実行" %>
                </div>    
            <% end %>
            <div class="border-top text-center">
                <%= link_to 'ジャンル検索', items_path%>
            </div>            
        </div>
        

    </div>

    <div class="col-md-10">
        <div class="m-2 h3 border-bottom">
          <div class="text-center">商品一覧</div>
        </div>        
            <div class="card-list-container py-5">
                <% @items.each do |item| %>
                <div class="card w-50 h-50 mt-4 shadow-lg">
                <% if item.is_active %>
            
                      
                            <%= image_tag item.get_image, class:"card-img-top"; %>
                      
                    <div class="card-body">
                        <div class="row">
                            <h4 class="card-title"><%= link_to item.name, item_path(item.id) %></h4>    
                            <h4 class="card-text">￥<%= item.with_tax_price.to_s(:delimited) %></h4>
                            <h5 class="card-text">コメント数<%= item.item_comments.count %></h5>
                        </div>    
                    </div>
                  
                    <% end %>
                    
                </div>
                <% end %>
                <div class="h4 text text-center"><%= paginate @items %></div>
            </div>
        
    </div>
</div>    

app/views/user/items/show.html.erb
<div class="container">
    <div class="m-2 h3 border-bottom">
      <div class="text-center">商品の登録情報</div>
    </div>            
    <div class="row">
        <div class="col-md-5">
            <h4>商品の画像</h4>
                <div class="card-list-container py-5">
                    <div class="w-200 mx-2 shadow-lg">
                        <%= image_tag @item.get_image, class:"card-img-top"; %>
                    </div>   
                </div>    
        </div>
        <div class="col-md-7 mt-5">
            <div class="row justify-content-start">
                <div class="col-3 border borderless bg-light">商品名</div>
                <div class="col-6 border border-dark"><%= @item.name %></div>
            </div>
            <div class="row justify-content-start">
                <div class="col-3 border borderless bg-light">商品説明</div>
                <div class="col-6 border border-dark"><%= @item.introduction %></div>
            </div>
            <div class="row justify-content-start">
                <div class="col-3 border borderless bg-light">値段</div>
                <div class="col-6 border border-dark">￥<%= @item.with_tax_price.to_s(:delimited) %>(税込)</div>
            </div>
            <%= form_with model: Simulation.new do |f| %>
                <div class="row justify-content-start">
                    <div class="col-3 border-start bg-light">
                        <%= f.hidden_field :item_id, :value => @item.id %>
                        <%= f.select :amount, *[1..10] %>                                
                    </div>
                    <div class="col-6 border-start border-dark"><%= f.submit "シミュレーションに加える", class: "btn btn-success" %></div>
                </div> 
            <% end %> 
            <div class="mt-5">  
               平均評価:
                <% if @item.item_comments.count !=0 %>
                    <%= (@item.item_comments.sum {|comment| comment.rate } / @item.item_comments.count).round(1)  %>
                <% else %>
                    まだ評価されていません
                <% end %>
                
                <%= form_with model: [@item, @item_comment] do |f| %>
                     <div id="post_raty">
                       <label>評価：</label>
                 
                    </div>
                    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
                    <%= f.submit "送信する" %>
                <% end %>
                      <script>
                    var elem = document.getElementById('post_raty');
                    var opt = {  
                        starOn: "<%= asset_path('star.jpg') %>",
                        starOff: "<%= asset_path('star_off.jpg') %>",
                        starHalf: "<%= asset_path('star_harf.jpg') %>",
                      };
                      raty(elem,opt);
                    </script>
            </div>            
        </div>
    </div>
</div>        


<div class="container">
    <div class="row">
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th>ユーザー名</th>
                    <th>コメント</th>
                    <th>コメント件数</th>
                    <th><%= @item.item_comments.count %></th>
                </tr>
            </thead>
            <tbody>
                <% @item.item_comments.each do |item_comment| %>
                <tr>
                    <td><%= item_comment.user.first_name %><%= item_comment.user.last_name %></td>
                    <td><%= item_comment.comment %></td>
                    <td><%= item_comment.created_at.strftime('%Y/%m/%d') %></td>
                    <td>
                        <% if item_comment.user == current_user %>
                            <%= link_to "削除", item_item_comment_path(item_comment.item, item_comment), method: :delete %>
                        <% end %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>