config/routes.rb
Rails.application.routes.draw do

    namespace :user do
      get 'homes/top'
      get 'homes/about'
    end
    namespace :admin do
      get 'homes/top'
    end
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
    namespace :admin do
      root to: 'homes#top'
      resources :users, only: [:index, :show, :edit, :update]
      resources :genres, only: [:new, :index, :create, :edit, :update]
      resources :items, only: [:new, :index, :create, :show, :edit, :update] do
        resources :item_comments, only: [:index, :destroy]
      end  
      resources :reviews, only: [:index, :show, :edit, :update, :destroy]
      resources :comments, only: [:index, :edit, :destroy, :update, :show]
    end
    
  
    devise_for :users,skip: [:passwords], controllers: {
      registrations: "user/registrations",
      sessions: 'user/sessions'
    }
    

    scope module: :user do
      devise_scope :user do
         post 'users/guest_sign_in', to: 'sessions#new_guest'
      end  
      root to: 'homes#top'

      get 'homes/about' => 'homes#about', as: 'about'
      resources :cows
      resources :pigs
      resources :hens
      get 'items/search' => 'items#search', as: 'search'      
      resources :items, only: [:index, :show] do
        resources :item_comments, only: [:create, :index, :destroy]
      end  
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
      get 'managements/check' => 'managements#check', as: 'check'
      resources :managements, only: [:new, :index, :edit, :create, :update, :show, :destroy]
      resources :reviews, only: [:new, :index, :edit, :create, :update, :show, :destroy]
      get 'users/mypage' => 'users#mypage', as: 'mypage'
      get 'users/show' => 'users#show', as: 'show' 
      get 'users/edit' => 'users#edit', as: 'edit'
      get 'users/confirm' => 'users#confirm', as: 'confirm'
      patch 'users/update' => 'users#update', as: 'update'
      patch 'users/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    
      delete 'simulations/destroy_all' => 'simulations#destroy_all', as: 'destroy_all'
      resources :simulations, only: [:index, :update, :destroy, :create]
    end  

  
  
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user.id)
  end
  
  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/user/addresses_controller.rb
class User::AddressesController < ApplicationController
  def edit
  end

  def index
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/cows_controller.rb
class User::CowsController < ApplicationController
   before_action :authenticate_user! 
   
   before_action :guest_check
   
  def guest_check
      if current_user.email=='guest@example.com'
        redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
      end
  end        
   
  def new
    @cow = Cow.new    
  end
  
  def create
    @cow = Cow.new(cow_params)
    @cow.user_id = current_user.id
    if @cow.save
      flash[:notice] ='牛の情報を登録しました！'
      redirect_to cow_path(@cow.id)
    else
      @cows = Cow.all
      render :index
    end  
  end    

  def index
    @cows = current_user.cows.all
  end

  def show
    @cow = Cow.find(params[:id])
  end
  
  def edit
    @cow = Cow.find(params[:id])
  end
  
  def update
    @cow = Cow.find(params[:id])
    if @cow.update(cow_params)
      flash[:notice] ='牛の情報を更新しました！'
      redirect_to cow_path(@cow.id)
    else
      render :edit
    end  
  end
  
  def destroy
    @cow = Cow.find(params[:id])
    @cow.destroy
    redirect_to cows_path    
  end
  
  private
  def cow_params
    params.require(:cow).permit(:user_id, :image, :name, :animal_name, :comment, :vaccine, :arrival, :estimated, :mating, :number, :is_active)
  end
end

app/controllers/user/hens_controller.rb
class User::HensController < ApplicationController
  before_action :authenticate_user!  
  
  before_action :guest_check
   
  def guest_check
      if current_user.email=='guest@example.com'
        redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
      end
  end        
   
  def new
    @hen = Hen.new    
  end
  
  def create
    @hen = Hen.new(hen_params)
    @hen.user_id = current_user.id
    if @hen.save
      flash[:notice] ='鶏の情報を登録しました！'
      redirect_to hen_path(@hen.id)
    else
      @hens = Hen.all
      render :index
    end  
  end    

  def index
    @hens = current_user.hens.all
  end

  def show
    @hen = Hen.find(params[:id])
  end
  
  def edit
    @hen = Hen.find(params[:id])
  end
  
  def update
    @hen = Hen.find(params[:id])
    if @hen.update(hen_params)
      flash[:notice] ='鶏の情報を更新しました！'
      redirect_to hen_path(@hen.id)
    else
      render :edit
    end  
  end
  
  def destroy
    @hen = Hen.find(params[:id])
    @hen.destroy
    redirect_to hens_path    
  end
  
  private
  def hen_params
    params.require(:hen).permit(:user_id, :animal_name, :comment, :vaccine, :arrival, :amount, :is_active, :image)
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top

  end

  def about
  end
  
end

app/controllers/user/item_comments_controller.rb
class User::ItemCommentsController < ApplicationController
     before_action :authenticate_user!

     before_action :guest_check
     
    def guest_check
        if current_user.email=='guest@example.com'
          redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
        end
    end     

    def create
        item = Item.find(params[:item_id])
        comment = current_user.item_comments.new(item_comment_params)
        comment.item_id = item.id
       if  comment.save
        redirect_to item_path(item)
       else
      redirect_to item_path(item)
       end
        
    end
    
    def destroy
        ItemComment.find(params[:id]).destroy
        redirect_to item_path(params[:item_id])
    end
    
    
    private
    
    def item_comment_params
        params.require(:item_comment).permit(:comment).merge({rate: params[:score]})
    end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
      def search
        @genres = Genre.all        
        if params[:genre_id].present?
          @items = Item.where(genre_id: params[:genre_id]).page(params[:page]).per(4)
        else
          @items = Item.page(params[:page]).per(4)
        end  
      end
  
    def index
        @genres = Genre.all
        if params[:genre_id]
            @genre = Genre.find(params[:genre_id])
            all_items = @genre.items
        else
            all_items = Item.all
        end
        @items = all_items.page(params[:page]).per(4)
    end
    
    def show
        @item = Item.find(params[:id])
        @item_comment = ItemComment.new
    end
    

        
    private
    def item_params
        params.require(:item).permit(:image, :name, :introduction, :price, :is_active, :genre_id)
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/pigs_controller.rb
class User::PigsController < ApplicationController
   before_action :authenticate_user!  
   
   before_action :guest_check
   
  def guest_check
      if current_user.email=='guest@example.com'
        redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
      end
  end        
   
  def new
    @pig = Pig.new    
  end
  
  def create
    @pig = Pig.new(pig_params)
    @pig.user_id = current_user.id
    if @pig.save
      flash[:notice] ='豚の情報を登録しました！'
      redirect_to pig_path(@pig.id)
    else
      @pig = Pig.all
      render :index
    end  
  end    

  def index
    @pigs = current_user.pigs.all
  end

  def show
    @pig = Pig.find(params[:id])
  end
  
  def edit
    @pig = Pig.find(params[:id])
  end
  
  def update
    @pig = Pig.find(params[:id])
    if @pig.update(pig_params)
      flash[:notice] ='豚の情報を更新しました！'
      redirect_to pig_path(@pig.id)
    else
      render :edit
    end  
  end
  
  def destroy
    @pig = Pig.find(params[:id])
    @pig.destroy
    redirect_to pigs_path    
  end
  
  private
  def pig_params
    params.require(:pig).permit(:user_id, :name, :animal_name, :comment, :vaccine, :arrival, :estimated, :mating, :number, :is_active, :image)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
  #   super(resource)
  show_path(current_user)
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_status, only: [:create]
  
  def after_sign_in_path_for(resource)
    show_path(current_user)
  end
    
  def after_sign_out_path_for(resource)
    user_homes_top_path
  end
  
  def new_guest
    user = User.guest
    sign_in user
    redirect_to items_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
  def user_status
    @user = User.find_by(email: params[:user][:email])
    return if !@user
     if @user.valid_password?(params[:user][:password]) && !@user.is_active 
       redirect_to new_user_registration_path
     end  
  end  
end

app/controllers/user/simulations_controller.rb
class User::SimulationsController < ApplicationController
     before_action :authenticate_user!

     before_action :guest_check
     
    def guest_check
        if current_user.email=='guest@example.com'
          redirect_to user_homes_top_path,notice: "このページを見るには会員登録が必要です。"
        end
    end     
     
    def index
        @simulations = current_user.simulations.all
        @all_price = @simulations.inject(0) { |sum, item| sum + item.sum_of_price }
    end
    
    def create
        @simulation = current_user.simulations.new(simulation_params)
        @simulation_already = current_user.simulations.find_by(item_id: params[:simulation][:item_id])
        if current_user.simulations.find_by(item_id: params[:simulation][:item_id])
            @new_amount = @simulation.amount + @simulation_already.amount
            @simulation_already.update(amount: @new_amount)
            redirect_to simulations_path
        else
            @simulation.save
            redirect_to simulations_path 
        end
        
        
    end
    
    def update
        @simulation = Simulation.find(params[:id])
        @simulation.update(simulation_params)
        redirect_to simulations_path
    end
    
    def destroy
        @simulation = Simulation.find(params[:id])
        @simulation.destroy
        redirect_to simulations_path
    end
    
    def destroy_all
        @simulations = current_user.simulations.all
        @simulations.destroy_all
        redirect_to simulations_path
    end
    
    private
    def simulation_params
        params.require(:simulation).permit(:user_id, :item_id, :amount)
    end    
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def confirm
    @user = current_user    
  end

  def show
    @user = current_user
  end
  
  def mypage
    @user = current_user
    @cows = current_user.cows.all
    @hens = current_user.hens.all
    @pigs = current_user.pigs.all
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    @user.update(user_params)
    redirect_to show_path
  end
    
  def withdrawal
    current_user.update(is_active: false)
    reset_session
    redirect_to  user_homes_top_path
  end
    
  private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end
        
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/addresses_helper.rb
module User::AddressesHelper
end

app/helpers/user/cows_helper.rb
module User::CowsHelper
end

app/views/user/users/confirm.html.erb
<div class="container">
    <div class="mt-5 row text-center">
        <div class="col h2">本当に退会しますか？</div>
    </div>
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="危険:">
            <use xlink:href="#exclamation-triangle-fill"/>
        </svg>
        <div>
            退会しようとしています！
        </div>
    </div>
    <div class="mt-5 row">    
        <div class="col text-center">
            退会すると、会員登録情報や
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            これまでの購入履歴が閲覧できなくなります。
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            退会する場合は、「退会する」をクリックしてください。
        </div>
    </div>
    <div class="row mt-5">
        <div class="col text-center m-3">
            <%= link_to show_path(current_user.id) do %>
                <button type="button" class="btn btn-info">退会しない</button>
            <% end %>
            <%= link_to withdrawal_path, method: :patch do %>
                <button type="button" class="btn btn-danger">退会する</button>
            <% end %>
            
        </div>
    </div>
</div>
<div class="row">
    
</div>    

app/views/user/users/edit.html.erb
<div class="m-2 h3 border-bottom">
  <div class="text-center">会員登録情報編集</div>
</div>


  <%= form_with model: @user, url: update_path, method: :patch do |f| %>
    <div class="my-3 row justify-content-start">
      <div class="col-2">氏名</div>
      <div class="col-3 rounded">
        <%= f.text_field :last_name %>
      </div>
      <div class="col-3 rounded">
        <%= f.text_field :first_name %>
      </div>
    </div>  
    
    <div class="my-3 row justify-content-start">
      <div class="col-2">フリガナ</div>
      <div class="col-3 rounded">
        <%= f.text_field :last_name_kana %>
      </div>
      <div class="col-3 rounded">
        <%= f.text_field :first_name_kana %>
      </div>  
    </div>
    
    <div class="my-3 row justify-content-start">
      <div class="col-2">郵便番号</div>
      <div class="col-3 rounded">
        <%= f.text_field :postal_code %>
      </div>
    </div>
    
    <div class="my-3 row justify-content-start">
      <div class="col-2">住所</div>
      <div class="col-9 rounded">
        <%= f.text_field :address %>
      </div>
    </div>
  
    <div class="my-3 row justify-content-start">
      <div class="col-2">電話番号</div>
      <div class="col-3 rounded">
        <%= f.text_field :telephone_number %>
      </div>
    </div>
    
    <div class="my-3 row justify-content-start">
      <div class="col-2">メールアドレス</div>
      <div class="col-3 rounded">
        <%= f.text_field :email %>
      </div>
    </div>
   
  <div class="row">
    <div class="col-2">
      <input class="btn btn-success" type="submit" value="変更内容を保存">
    </div> 
    
     
    <div class="col-10">
      <%= link_to confirm_path do %>
        <div class="btn btn-sm btn-danger">退会する</div>
      <% end %>
    </div>
  </div>  
  <% end %>  

app/views/user/users/mypage.html.erb
<div class="m-2 h3 border-bottom">
  <div class="text-center">登録情報一覧</div>
</div>


        <div class="row mt-5">
            <div class="col-md-4">   
                <%= link_to cows_path(current_user) do %>
                    <div class="btn btn-sm btn-secondary rounded-pill">登録した牛一覧</div>
                <% end %>
                <%= link_to new_cow_path(current_user) do %>
                    <div class="btn btn-sm btn-info rounded-pill">牛の新規登録</div>
                <% end %>                
            </div>                         
            <div class="col-md-4">   
                <%= link_to pigs_path(current_user) do %>
                    <div class="btn btn-sm btn-secondary rounded-pill">登録した豚一覧</div>
                <% end %>
                <%= link_to new_pig_path(current_user) do %>
                    <div class="btn btn-sm btn-info rounded-pill">豚の新規登録</div>
                <% end %>                
            </div>                         
            <div class="col-md-4">   
                <%= link_to hens_path(current_user) do %>
                    <div class="btn btn-sm btn-secondary rounded-pill">登録した鶏一覧</div>
                <% end %>
                <%= link_to new_hen_path(current_user) do %>
                    <div class="btn btn-sm btn-info rounded-pill">鶏の新規登録</div>
                <% end %>                
            </div>                                     
        </div>
    <section id="menu">
            <ul class="nav nav-tabs mt-5">
                    <li class="nav-item"><a href="#content1" class="nav-link active" data-toggle="tab">乳用牛・肥育牛</a></li>
                    <li class="nav-item"><a href="#content2" class="nav-link" data-toggle="tab">豚</a></li>
                    <li class="nav-item"><a href="#content3" class="nav-link" data-toggle="tab">鶏卵・肉用鶏</a></li>
            </ul>

            
            <div class="tab-content">
                <div id="content1" class="tab-pane active">
                    <table class="table table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>個体名</th>
                                <th>個体番号</th>
                            </tr>
                        </thead>
                        <tbody>
                        <% @cows.each do |cow| %>
                            <tr>
                                <td>
                                    <%= link_to cow_path(cow.id) do %>
                                        <%= cow.name %>
                                    <% end %>                                        
                                </td>
                                <td><%= cow.number %></td>
                            </tr>
                        <% end %>    
                        </tbody>
                    </table>
                </div>
                <div id="content2" class="tab-pane">
                     <table class="table table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>個体名</th>
                                <th>品種名</th>
                            </tr>
                        </thead>
                        <tbody>
                        <% @pigs.each do |pig| %>
                            <tr>
                                <td>
                                    <%= link_to pig_path(pig.id) do %>
                                        <%= pig.name %>
                                    <% end %>                                              
                                </td>
                                <td><%= pig.animal_name %></td>
                            </tr>
                        <% end %>    
                        </tbody>
                    </table>
                </div>
                <div id="content3" class="tab-pane">
                     <table class="table table-hover">
                        <thead class="table-light">
                            <tr>
                                <th>品種名</th>
                                <th>羽数</th>
                            </tr>
                        </thead>
                        <tbody>
                        <% @hens.each do |hen| %>
                            <tr>
                                <td>
                                    <%= link_to hen_path(hen.id) do %>
                                        <%= hen.animal_name %>
                                    <% end %>                                              
                                </td>
                                <td><%= hen.amount %></td>
                            </tr>
                        <% end %>    
                        </tbody>
                    </table>
                </div>                
            </div>
            
    </section>

app/views/user/users/show.html.erb
<div class="m-2 h3 border-bottom">
  <div class="text-center">マイページ</div>
</div>

<div class="container">
    
    <div class="my-3 row justify-content-start">
        <div class="col-2 h4">登録情報</div>
        <div class="col-4">   
            <%= link_to edit_path(current_user) do %>
                <div class="btn btn-sm btn-success rounded-pill">編集する</div>
            <% end %>
        </div> 
        <div class="col-4">   
            <%= link_to mypage_path(current_user) do %>
                <div class="btn btn-sm btn-secondary rounded-pill">登録した家畜一覧</div>
            <% end %>
        </div>             
    </div>
    <div class="row justify-content-start">
        <div class="col-3 border border-dark bg-light">氏名</div>
        <div class="col-6 border border-dark"><%= current_user.last_name %><%= current_user.first_name %></div>
    </div>
    <div class="row justify-content-start">
        <div class="col-3 border border-dark bg-light">カナ</div>
        <div class="col-6 border border-dark"><%= current_user.last_name_kana %><%= current_user.first_name_kana %></div>
    </div>
    <div class="row justify-content-start">
        <div class="col-3 border border-dark bg-light">郵便番号</div>
        <div class="col-6 border border-dark"><%= current_user.postal_code %></div>
    </div>
    <div class="row justify-content-start">
        <div class="col-3 border border-dark bg-light">住所</div>
        <div class="col-6 border border-dark"><%= current_user.address %></div>
    </div>
    <div class="row justify-content-start">
        <div class="col-3 border border-dark bg-light">電話番号</div>
        <div class="col-6 border border-dark"><%= current_user.telephone_number %></div>
    </div>
    <div class="row justify-content-start">
        <div class="col-3 border border-dark bg-light">メールアドレス</div>
        <div class="col-6 border border-dark"><%= current_user.email %></div>
    </div>
    <% Item.all.each do |item| %>
        <div class="row justify-content-start">
        <% if item.item_comments.where(user_id: current_user.id).count > 0 %>    
            <%= link_to "#{item.item_comments.where(user_id: current_user.id).count} コメント", item_path(item.id) %>
        <% end %>    
        </div>
    <% end %>

</div>